### ISSUE TITLE
API Tính giai thừa

### ISSUE THREAD

**Issue by khuonglnguyen** [khuonglnguyen/math-api#24]
URL: /giaithua?number=8
Response example: { result: 40320 }

**Comment by karshoul** [comment]
![Uploading Screenshot 2023-12-23 085925.png…]()

**Comment by karshoul** [comment]
![image](https://github.com/khuonglnguyen/math-api/assets/76602336/571ab6ef-fc11-4954-aae3-6a3976561dcd)
